---
#####################################
### Create service users
#####################################

- name: Create service users
  microsoft.ad.user:
    name: '{{ item }}'
    password: '{{ dc_password_service }}'
    state: present
    path: '{{ dc_ou_user_service }}'
  with_items: '{{ dc_user_service }}'

#####################################
### Create standard users statically
#####################################

- name: Create standard users statically
  microsoft.ad.user:
    name: '{{ item }}'
    password: '{{ dc_password_user }}'
    state: present
    path: '{{ domain_ou_user }}'
  with_items: '{{ dc_user_standard }}'
  when: dc_user_standard is defined

#####################################
### Create standard users dynamically
#####################################

- name: Printe the standard users dynamically
  ansible.builtin.debug:
    msg: "Name: {{ item.0 | replace('##', item.1) }} - Path: {{ domain_ou_user }}| replace('##', item.1) }}"
  with_nested:
  - '{{ dc_user_standard_dynamic }}'
  - '{{ range(1, dc_domain_count + 1, 1) | list }}'
  when: dc_user_standard_dynamic is defined
  
- name: Create standard users dynamically
  microsoft.ad.user:
    name: "{{ item.0 | replace('##', item.1) }}"
    password: '{{ dc_password_user }}'
    state: present
    path: "{{ domain_ou_user }}| replace('##', item.1) }}"
  with_nested:
  - '{{ dc_user_standard_dynamic }}'
  - '{{ range(1, dc_domain_count + 1, 1) | list }}'
  when: dc_user_standard_dynamic is defined