---
#####################################
### Create admin users
#####################################

- name: Ensure user domainjoin is present in OU=Admins,OU=Accounts,OU=Objects,DC=dt,DC=democloud
  community.windows.win_domain_user:
    name: '{{ item }}'
    password: '{{ domainjoin_user_pw }}'
    state: present
    path: '{{ dc_ou_admins }}'
  loop:
     - domainjoin

#####################################
### Create service users
#####################################

- name: Ensure user svc_ldap is present in OU=Services,OU=Accounts,OU=Objects,DC=dt,DC=democloud
  community.windows.win_domain_user:
    name: '{{ item }}'
    password: '{{ dc_password_service }}'
    state: present
    path: '{{ dc_ou_services }}'
  loop:
     - svc_ldap

#####################################
### Create normal users
#####################################

- name: Ensure users are present in OU=User,OU=Accounts,OU=Objects,DC=dt,DC=democloud
  community.windows.win_domain_user:
    name: '{{ item }}'
    password: '{{ dc_password_user }}'
    state: present
    path: '{{ dc_ou_user }}'
  loop:
     - demo
     - demo01
     - demo02
     - demo03
     - demo04
     - demo05
     - demo06
     - demo07
     - demo08
     - demo09
     - demo10

# Source: https://docs.ansible.com/ansible/latest/collections/community/windows/win_domain_ou_module.html
# ansible-galaxy collection install community.windows
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html