---
#####################################
### Create service users
#####################################

- name: Ensure service users are present in given OU
  microsoft.ad.user:
    name: '{{ item }}'
    password: '{{ dc_password_service }}'
    state: present
    path: '{{ dc_ou_user_service }}'
  with_items: '{{ dc_user_service }}'

#####################################
### Create standard users
#####################################

- name: Ensure standard users are present in given OU
  microsoft.ad.user:
    name: '{{ item }}'
    password: '{{ dc_password_user }}'
    state: present
    path: '{{ dc_ou_user_standard }}'
  with_items: '{{ dc_user_standard }}'