---
#####################################
### Create service users
#####################################

- name: Ensure service users are present in given OU
  microsoft.ad.user:
    name: '{{ item }}'
    password: '{{ dc_password_service }}'
    state: present
    path: '{{ dc_ou_user_service }}'
  with_items: '{{ dc_user_service }}'

#####################################
### Create standard users
#####################################

- name: Ensure standard users are present in given OU
  microsoft.ad.user:
    name: '{{ item }}'
    password: '{{ dc_password_user }}'
    state: present
    path: '{{ dc_ou_user_standard }}'
  with_items: '{{ dc_user_standard }}'
  when: dc_user_standard is defined

#####################################
### Create standard users dynamically
#####################################

- name: Ensure standard users are present in given OU
  microsoft.ad.user:
    name: '{{ item.0 | replace('##', item.1) }}'
    password: '{{ dc_password_user }}'
    state: present
    path: '{{ dc_ou_user_standard }}'
  with_nested:
  - "{{ dc_user_standard_dynamic }}"
  - "{{ range(1, dc_domain_count + 1, 1) | list }}"
  when: dc_user_standard_dynamic is defined