---
#####################################
### Create service users
#####################################

- name: Ensure user svc_ldap is present
  community.windows.win_domain_user:
    name: '{{ item }}'
    password: '{{ dc_password_service }}'
    state: present
    path: '{{ dc_ou_services }}'
  with_items: "{{ users.service }}"

#####################################
### Create normal users
#####################################

- name: Ensure users are present in
  community.windows.win_domain_user:
    name: '{{ item }}'
    password: '{{ dc_password_user }}'
    state: present
    path: '{{ dc_ou_user }}'
  with_items: "{{ users.standard }}"

# Source: https://docs.ansible.com/ansible/latest/collections/community/windows/win_domain_ou_module.html
# ansible-galaxy collection install community.windows
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html