---
#####################################
### Create service users
#####################################

- name: Create service users statically
  microsoft.ad.user:
    name: '{{ item }}'
    password: '{{ dc.domain.passwords.service }}'
    state: present
    path: '{{ dc.domain.ou.accounts_service }}'
    password_never_expires: true
    user_cannot_change_password: true
  with_items: '{{ dc.domain.user.service }}'

#####################################
### Create standard users statically
#####################################

- name: Create standard users statically
  microsoft.ad.user:
    name: '{{ item }}'
    password: '{{ dc.domain.passwords.user }}'
    state: present
    path: '{{ dc.domain.ou.accounts_user }}'
    password_never_expires: true
    user_cannot_change_password: true
  with_items: '{{ dc.domain.user.standard }}'
  when: dc.domain.user.standard is defined

#####################################
### Create standard users dynamically
#####################################

- name: Create standard users dynamically
  microsoft.ad.user:
    name: "{{ item.0 | replace('##', item.1) }}"
    password: '{{ dc.domain.passwords.user }}'
    password_never_expires: true
    user_cannot_change_password: true
    state: present
    path: "{{ dc.domain.ou.accounts_user | replace('##', item.1) }}"
  with_nested:
  - '{{ dc.domain.user.standard_dynamic }}'
  - '{{ range(1, dc_domain_count + 1, 1) | list }}'
  when: dc.domain.user.standard_dynamic is defined